### ISSUE TITLE
2018_00_HTML5

### ISSUE THREAD

**Issue by jqlancer** [jqlancer/blog#1]
从来没有系统的看过书，故而分不清H5 C3和以前的版本到底有何区别，
昨天在图书馆看了本讲这方面的书，故而做一个摘记。

### HTML5比较重要的特性
1. **即使浏览器不支持H5，也会渲染**
`<!DOCTYPE html>`

2. **带标题的图片**
``` html
<figure>
    <img src="" alt="">
    <figcaption>this is a figure</figcaption>
</figure>  
```

3. **link script无需加type属性**

4. **元素可编辑**
``` html
<div contenteditable="true" />
```

5. **input属性**
``` html
<input type="email" /> <!-- 提交时会验证是否为email格式 -->
<input placeholder="type your name here" /> <!-- 输入框默认的显示文字 -->
<input name="pwd" required autofocus />  <!-- 不许为空 必填 / 自动获取光标 -->
<input type="range" />  <!-- 滑块 -->
```

6. **语义化标签or元素**
header footer hgroup /  article section nav aside
mark：高亮文本

7. **audio video canvas**

8. **正则表达式可以用在input元素中**
``` html
<input pattern="[A^Z]" />
```

9. **local storage**
cookie存储大小只有4k，web存储可以达到5M或以上
localStorage：长期，方法有setItem/getItem/removeItem/clear
sessionStorage: 关闭窗口后数据清除
webSQL：存储大量数据（如同数据库）

10. **缓存**
a)创建配置文件
``` appcache
CACHE MANIFEST
CACHE:
#此处写需要缓存在本地的资源文件
NETWORK:
#此处指定不进行本地缓存的文件
FALLBACK:
#
```

``` html
<html manifest="../xxx.manifest">
</html>
```

### CSS3重要特性
1. **属性选择器**
``` css
p[id*='new']  /* id 包含new的p元素 */
p[id^='new']  /* id 以new开头的p元素 */
p[id$='new']  /* id以new结尾的p元素 */

/* 伪类 */
/* 特定顺序 不能乱 否则无法正常显示 */
a:link {color: black}
a:visited {color: red}
a:hover {color: yellow}
a:active {color: blue}

p:first-child  /* 每一个层内 第一个p元素 */
p:last-child  /* 每一个层内 最后一个p元素 */
p:nth-child(3) 
p:nth-child(odd/even)
p:nth-child(2n+1)
nth-of-type / only-child / empty / target.....
p:first-child:first-letter

div::before /* 在div前插入内容 */
div:after  /* 在div后插入内容 */

div p /* div下所有的p */
div>p /* div直属的p */
div+p /* div与p同级别，紧跟在div后的那个p */
div~p /* div与p同级别，div后所有同级别的p*/
```

2. **透明度**
rgba  /  opacity

3. **多栏布局**
-moz-column-count

4. **多个背景图片 边框图片**

5. **box-shadow**
    text-shadow

6. **border-radius**

7. **媒体查询**

8. **嵌入字体类型**
``` css
/* 使用服务器已安装的字体 */
@font-face {
    font-family: ....; 
    src: ...:
}
```

9. **变形效果**
``` css
transform: translate(x, y)   /* 平移 */
transform: scale(x, y)         /* 缩放 */
transform: rotate(angle)     /* 旋转 */
```

10. **过渡效果**
``` css
background-color: red;
transition: background-color 5s linear 1s;
/* 等待1s（delay）用5s（duration）后过渡到当前颜色 */
```

11. **动画效果**
``` css
/* 第一步：创建关键帧（动画） */
@keyframes 'appear' {
    from {opacity:0;}
    to {opacity 1:}
}
/* 第二步：使用 */
p {
    animation: 'appear' 5s ease-in 4ms;
}
```
